### ISSUE TITLE
license

### ISSUE THREAD

**Issue by hiroki-kojima** [diegodox/rangecoder-cpp17#13]
Can you tell me the license?

**Comment by diegodox** [comment]
@hiroki-kojima 
Would you mind if I choose MIT license?

**Comment by hiroki-kojima** [comment]
@diegodox lgtm

**Comment by hiroki-kojima** [comment]
I would appreciate if you could add the license to the repository.

https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository
