### ISSUE TITLE
Arguments that are not updated by the function

### ISSUE THREAD

**Issue by hiroki-kojima** [diegodox/rangecoder-cpp17#2]
Wouldn't it be better to make variables like the title of this issue explicitly constant?

For example,  `Pmodel`  to input for `encode`:

https://github.com/diegodox/rangecoder-cpp17/blob/7c0b48da9a885e428a4bc96600c3f604912c0451/rangecoder.h#L168

-> 
```C++
auto encode(const PModel &pmodel, int index) -> int 
```

**Comment by diegodox** [comment]
@hiroki-kojima 
Seems nice. Do you plan to create pull request?
