### ISSUE TITLE
icc support

### ISSUE THREAD

**Issue by diegodox** [diegodox/rangecoder-cpp17#7]
Currently, `std::optional` is not supported by icc.

**Comment by diegodox** [comment]
@hiroki-kojima 

Should we implement using ifdef on another branch?

**Comment by hiroki-kojima** [comment]
Perhaps it is preferable to use macro. version control is easy.

**Comment by diegodox** [comment]
I just delete dependency of `std::optional`.
So, no macros added and no branch needed.

**Comment by hiroki-kojima** [comment]
@diegodox 
request re-discussion about this.

https://github.com/diegodox/rangecoder-cpp17/pull/6

**Comment by diegodox** [comment]
@hiroki-kojima 
Let's disscuss on #6, pull-request reopened.
